// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MusicGame","status":true,"description":"","parameters":{}},
{"name":"Story Book Ex v2","status":false,"description":"","parameters":{}}
];
