// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Story Book Ex v2","status":false,"description":"","parameters":{}},
{"name":"MusicGame_Input","status":true,"description":"","parameters":{}},
{"name":"MusicGame_Manager","status":true,"description":"","parameters":{}},
{"name":"MusicGame_Object","status":true,"description":"","parameters":{}},
{"name":"MusicGame_Overload","status":true,"description":"","parameters":{}},
{"name":"MusicGame_Scene","status":true,"description":"","parameters":{}},
{"name":"MusicGame_Sprite","status":true,"description":"","parameters":{}}
];
